package dev.caecorthus.sparkassist.achievement;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Every achievement SparkAssist knows. Players never see this list: an achievement appears only once earned, and
 * several earned in one round unlock in this order. Ids go into players' saves and never change; the rules live in
 * {@link RoundRules}, {@link ConsumptionRules}, {@link KillRules}, {@link RoleSkillRules} and {@link TraitRules}.
 * SparkAssist 已知的全部成就。玩家看不到这份列表：成就只有在达成后才会出现，同一局达成的多个成就按此顺序解锁。
 * id 会写进玩家存档，永不修改；规则见 {@link RoundRules}、{@link ConsumptionRules}、{@link KillRules}、
 * {@link RoleSkillRules} 与 {@link TraitRules}。
 */
public final class AchievementCatalog {
    private static final List<Achievement> ALL = List.of(
            new Achievement("survivor", 1, "minecraft:totem_of_undying", "幸存者",
                    "在一次对局中存活",
                    RoundRules::survived),
            new Achievement("welcome_aboard", 1, "wathe:letter", "欢迎来到欧美列车",
                    "在开局 60 秒内死亡",
                    RoundRules::diedInFirstMinute),
            new Achievement("first_blood", 1, "wathe:knife", "初露锋芒",
                    "以杀手身份击杀一名玩家",
                    KillRules::killAsKiller),
            new Achievement("justice_served", 1, "minecraft:mace", "正义制裁",
                    "以警职击杀一名其他阵营的玩家",
                    KillRules::policeKillOfOtherSide),
            new Achievement("power_of_the_people", 1, "minecraft:trident", "群众的力量",
                    "以非警职的好人身份击杀一名其他阵营的玩家",
                    KillRules::civilianKillOfOtherSide),
            new Achievement("deputy_sheriff", 1, "wathe:revolver", "替补警长",
                    "以非警职的好人身份捡到一把左轮手枪",
                    RoleSkillRules::civilianPicksUpRevolver),
            new Achievement("restless_ghost", 1, "minecraft:ghast_tear", "幽幽鬼魂",
                    "成为一名冤魂",
                    RoundRules::becameWraith),
            new Achievement("hooked_on_food", 1, "minecraft:cooked_beef", "好吃到上瘾",
                    "累计吃下 10 份食物",
                    ConsumptionRules::lifetimeFood),
            new Achievement("chug_chug", 1, "wathe:mojito", "吨吨吨",
                    "累计喝下 10 杯饮品",
                    ConsumptionRules::lifetimeDrinks),
            new Achievement("your_umbrella", 1, "minecraft:feather", "你的保护伞",
                    "成为一名守护天使并为一名玩家上盾",
                    RoleSkillRules::guardianShield),
            new Achievement("karma", 1, "sparkwitch:vendetta_knife", "因果报应",
                    "成为一名仇杀客并击杀凶手",
                    RoleSkillRules::vendettaKnife),
            new Achievement("windy_day", 1, "minecraft:wind_charge", "今天风太大了",
                    "成为一名风精灵并使用风弹导致一名玩家坠落下了列车",
                    RoleSkillRules::windSpiritFall),
            new Achievement("needs_repair", 1, "wathe:blackout", "你的车该修了",
                    "成为一名破坏者并破坏一次灯光",
                    RoleSkillRules::sabotagedLights),
            new Achievement("dizzy", 1, "minecraft:fermented_spider_eye", "脑袋晕晕的...",
                    "成为一名诅咒者并对其他玩家成功施加诅咒",
                    RoleSkillRules::cursedSomeone),
            new Achievement("thanks_to_you", 1, "sparkwitch:ceremonial_sword", "拜你所赐",
                    "以大魔女身份用仪礼剑封喉一名玩家",
                    KillRules::ceremonialBladeKill),
            new Achievement("perfect_cover", 1, "wathe:walkie_talkie", "完美伪装",
                    "以卧底身份击杀一名杀手",
                    KillRules::undercoverKillsKiller),
            new Achievement("mighty", 1, "minecraft:blaze_powder", "力大无穷",
                    "以预备魔女身份使用巨力击杀一名非好人",
                    KillRules::mightyForceKill),
            new Achievement("bloodlust_bared", 1, "minecraft:ender_eye", "杀意外露",
                    "以预备魔女身份在杀意感知期间击杀一名非好人",
                    KillRules::killDuringMurderSense),
            new Achievement("deja_vu", 2, "sparkstrength:skateboard", "逮虾户",
                    "以秃鹫身份在拥有速度的同时使用滑板",
                    RoleSkillRules::vultureSkatesWithSpeed),
            new Achievement("hungry_ghost", 2, "minecraft:bread", "饿鬼转世",
                    "一局内吃下 10 份食物",
                    ConsumptionRules::roundFood),
            new Achievement("water_ghost", 2, "wathe:champagne", "水鬼投胎",
                    "一局内喝下 10 杯饮品",
                    ConsumptionRules::roundDrinks),
            new Achievement("die_full", 3, "minecraft:cake", "死也得当个饱死鬼",
                    "在一局内吃下 10 份食物并死亡",
                    ConsumptionRules::roundFoodThenDied),
            new Achievement("waterlogged", 3, "minecraft:water_bucket", "积水潭",
                    "在一局内喝下 10 杯饮品并死亡",
                    ConsumptionRules::roundDrinksThenDied),
            new Achievement("deadly_view", 2, "sparkstrength:bomb_drone", "致命视角",
                    "以炸弹客身份使用自爆无人机一次击杀 3 名玩家",
                    KillRules::bombDroneTriple),
            new Achievement("point_blank", 2, "sparkwitch:usec_rifle", "危险零距离",
                    "以 USEC 身份在不开镜的情况下使用 AXMC 在 12 格及以内击杀一名玩家",
                    KillRules::unscopedCloseRifleKill),
            new Achievement("grenadier", 3, "sparkstrength:m67", "掷弹兵",
                    "使用一颗 M67 击杀 3 名玩家",
                    KillRules::grenadeTriple),
            new Achievement("deadly_calibration", 3, "minecraft:spyglass", "致命校准",
                    "以 USEC 身份使用 AXMC 在 50 格及以外击杀一名玩家",
                    KillRules::longRifleKill),
            new Achievement("got_you", 2, "sparkwitch:black_raven_mask", "逮到你了",
                    "作为善良黑羽鸦，感知到一名非好人",
                    RoleSkillRules::civilianRavenPerceivesOtherSide),
            new Achievement("last_meal", 4, "wathe:poison_vial", "断头饭",
                    "以服务员身份将毒师下过毒的饮食送回毒师的嘴里",
                    RoleSkillRules::servedPoisonerOwnPoison),
            new Achievement("hooked_on_blue", 2, "sparkstrength:blue_vitriol", "纯瘾大",
                    "以毒理学家身份在一局内获得蓝毒状态 5 次",
                    RoleSkillRules::toxicologistBlueFiveTimes),
            new Achievement("mgw", 2, "wathe:psycho_mode", "MGW",
                    "以杀手身份在疯魔状态下一次性击杀 8 名玩家",
                    KillRules::killerPsychoOctuple),
            new Achievement("boar_charge", 3, "minecraft:porkchop", "野猪冲撞",
                    "以皮革嘎的身份在皮革追击状态下一次性击杀 3 名非好人",
                    KillRules::pigGodChaseTriple),
            new Achievement("it_works", 2, "noellesroles:iron_man_vial", "我的药剂是有效的",
                    "以教授身份使用铁人药剂成功为其他玩家抵挡两次伤害",
                    RoleSkillRules::ironManBlocksTwice),
            new Achievement("grasping_at_wind", 2, "sparkstrength:magnifier", "捕风捉影",
                    "以侦探身份盘问到凶手",
                    RoleSkillRules::interrogatedTheKiller),
            new Achievement("sons_of_tara", 3, "noellesroles:base_spirit", "塔拉之子",
                    "以酒保身份在使用生死相依后的 10 秒内击杀一名非好人",
                    RoleSkillRules::killSoonAfterLifeAndDeath),
            new Achievement("within_seven_steps", 2, "wathe:derringer", "七步之内",
                    "拥有重炮手词条时击杀一位疯魔",
                    TraitRules::killPsychoWithHeavyArtillery),
            new Achievement("quick_justice", 2, "minecraft:clock", "反欧美",
                    "在同时拥有快手和快速装填词条时击杀一名在 60 秒内有击杀的非好人",
                    TraitRules::killRecentKillerWithFastHandsAndReload),
            new Achievement("long_shot", 2, "minecraft:target", "超远打击",
                    "在拥有 Niko 词条时使用左轮手枪击杀一名 35 格及以外的非好人",
                    TraitRules::longRevolverKillWithNiko),
            new Achievement("precision_guided", 2, "minecraft:skeleton_skull", "精确制导",
                    "以饕餮身份一次性发射三颗头颅导弹",
                    RoleSkillRules::taotieTripleVolley),
            new Achievement("depressed", 2, "wathe:bat", "我有抑郁症！！",
                    "在抑郁疯魔状态下击杀凶手",
                    TraitRules::killDepressionAttacker),
            new Achievement("haze", 2, "minecraft:ink_sac", "阴霾",
                    "以大魔女身份在 10 秒内在商店买下所有魔法",
                    RoleSkillRules::boughtEveryMagicQuickly),
            new Achievement("anti_armor", 2, "sparkwitch:anti_tank_launcher", "反载",
                    "以药炮手身份使用反坦克炮筒和 TR 弹一次性击杀 3 名玩家",
                    KillRules::potionShellTriple),
            new Achievement("democracy", 2, "sparkstrength:democracy_shield", "民主之力",
                    "以保镖身份使用民主之盾在一局内挡下 3 次攻击",
                    RoleSkillRules::democracyShieldBlocksThree),
            new Achievement("possession", 1, "minecraft:soul_lantern", "附身",
                    "以灵界行者身份附身至一名冤魂的视角",
                    RoleSkillRules::possessedWraith),
            new Achievement("snowball", 4, "minecraft:snowball", "滚雪球",
                    "以警职击杀过 2/3 杀手身份",
                    KillRules::policeKilledMostKillerRoles),
            new Achievement("snowball_plus", 5, "minecraft:snow_block", "滚雪球+",
                    "以警职一命击杀 2/3 杀手身份（可多局完成，但其中如果有一局为警职且死亡则重来）",
                    KillRules::policeKilledMostKillerRolesInOneLife),
            new Achievement("grand_slam", 4, "minecraft:gold_ingot", "大满贯",
                    "以杀手身份击杀 2/3 警职",
                    KillRules::killerKilledMostPoliceRoles),
            new Achievement("grand_slam_plus", 5, "minecraft:gold_block", "大满贯+",
                    "以杀手身份一命击杀 2/3 警职（可多局完成，但其中如果有一局为杀手且死亡则重来）",
                    KillRules::killerKilledMostPoliceRolesInOneLife),
            new Achievement("blood_feud", 4, "minecraft:wither_rose", "血仇",
                    "以大魔女身份击杀 2/3 警职和杀手",
                    KillRules::grandWitchKilledMostPoliceAndKillerRoles),
            new Achievement("strong_grow_weak", 2, "minecraft:red_banner", "强者愈弱...",
                    "触发背水一战",
                    TraitRules::triggeredLastStand),
            new Achievement("weak_grow_strong", 3, "minecraft:beacon", "而弱者愈强",
                    "触发背水一战后在场上还存在四名及以上非好人时获得胜利",
                    TraitRules::wonLastStandAgainstMany),
            new Achievement("show_off", 2, "minecraft:diamond", "展示豪度",
                    "以黑警身份在展示豪度状态下一局击杀 8 名玩家",
                    KillRules::showOffOctuple),
            new Achievement("dual_answer", 2, "sparkstrength:serial_pistol", "双枪会给出答案",
                    "以连环杀手身份在双枪疯魔状态下一局击杀 8 名玩家",
                    KillRules::serialKillerPsychoOctuple),
            new Achievement("savior", 4, "minecraft:nether_star", "救世主",
                    "在有四名及以上杀手的对局中击杀一半非好人",
                    KillRules::killHalfTheOtherSide),
            new Achievement("smoke_session", 2, "noellesroles:poison_gas_bomb", "抽大烟",
                    "以毒师身份使用毒气弹一局内击杀 4 名玩家",
                    KillRules::gasBombQuadruple),
            new Achievement("blessing", 2, "sparkwitch:holy_flash", "恩赐",
                    "使用圣光弹影响 3 名玩家",
                    RoleSkillRules::holyFlashThree),
            new Achievement("death_knell", 2, "sparkwitch:toll_bell", "丧钟为你而响",
                    "以敲钟人身份使用钟一次性收割 4 名玩家",
                    KillRules::bellTollQuadruple),
            new Achievement("blind_confidence", 2, "minecraft:shield", "盲目自信",
                    "拥有狭路相逢词条时举刀抵挡一次老兵的攻击",
                    TraitRules::parriedVeteran),
            new Achievement("not_undercover", 2, "sparkstrength:coroner_body_bag", "我不是卧底",
                    "以验尸官身份伪装成杀手并击杀一名玩家",
                    RoleSkillRules::killDisguisedAsKiller)
    );
    private static final Map<String, Achievement> BY_ID = index(ALL);

    private AchievementCatalog() {
    }

    public static List<Achievement> all() {
        return ALL;
    }

    public static Optional<Achievement> byId(String id) {
        return Optional.ofNullable(BY_ID.get(id));
    }

    static Map<String, Achievement> index(List<Achievement> achievements) {
        Map<String, Achievement> map = new LinkedHashMap<>();
        for (Achievement achievement : achievements) {
            if (map.put(achievement.id(), achievement) != null) {
                throw new IllegalStateException("Duplicate achievement id " + achievement.id());
            }
        }
        return Map.copyOf(map);
    }
}
